/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Carcara
 */
public class Programa extends javax.swing.JFrame {

   private File arquivo;

    /**
     * Creates new form Programa
     */
    public Programa() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        barraStatus = new javax.swing.JPanel();
        nomeArquivoStatus = new javax.swing.JLabel();
        nomeArquivo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuArquivoAbrir = new javax.swing.JMenuItem();
        menuArquivoFechar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuArquivoSair = new javax.swing.JMenuItem();
        menuAlgoritmos = new javax.swing.JMenu();
        menuAlgoritmosOrdenacao = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        menuAlgoritmosBusca = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();

        fileChooser.setDialogTitle("Abrir");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Capivara APP");

        barraStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nomeArquivoStatus.setText("Nenhum arquivo aberto");

        javax.swing.GroupLayout barraStatusLayout = new javax.swing.GroupLayout(barraStatus);
        barraStatus.setLayout(barraStatusLayout);
        barraStatusLayout.setHorizontalGroup(
            barraStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeArquivoStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        barraStatusLayout.setVerticalGroup(
            barraStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraStatusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(barraStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeArquivoStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(16, 40, 143));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");

        menuArquivoAbrir.setText("Abrir Arquivo");
        menuArquivoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoAbrirActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoAbrir);

        menuArquivoFechar.setText("Fechar Arquivo");
        menuArquivoFechar.setEnabled(false);
        menuArquivoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoFecharActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoFechar);
        menuArquivo.add(jSeparator1);

        menuArquivoSair.setText("Sair");
        menuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoSair);

        jMenuBar1.add(menuArquivo);

        menuAlgoritmos.setText("Algoritmos");
        menuAlgoritmos.setEnabled(false);

        menuAlgoritmosOrdenacao.setText("Ordenação (Sort)");

        jMenuItem4.setText("Sementes aleatórias (Cinco de cada)");
        menuAlgoritmosOrdenacao.add(jMenuItem4);
        menuAlgoritmosOrdenacao.add(jSeparator3);

        jMenuItem7.setText("Bubble Sort");
        menuAlgoritmosOrdenacao.add(jMenuItem7);

        jMenu7.setText("Quick Sort");

        jMenuItem8.setText("Quick Sort Recursivo");
        jMenu7.add(jMenuItem8);

        jMenuItem9.setText("Quick Sort Mediana");
        jMenu7.add(jMenuItem9);

        jMenuItem10.setText("Quick Sort Inserção");
        jMenu7.add(jMenuItem10);

        menuAlgoritmosOrdenacao.add(jMenu7);

        jMenuItem11.setText("Insertion Sort");
        menuAlgoritmosOrdenacao.add(jMenuItem11);

        jMenuItem12.setText("Merge Sort");
        menuAlgoritmosOrdenacao.add(jMenuItem12);

        jMenuItem13.setText("Heap Sort");
        menuAlgoritmosOrdenacao.add(jMenuItem13);

        jMenuItem14.setText("Capivara Sort");
        menuAlgoritmosOrdenacao.add(jMenuItem14);

        menuAlgoritmos.add(menuAlgoritmosOrdenacao);

        menuAlgoritmosBusca.setText("Busca (Hash)");
        menuAlgoritmos.add(menuAlgoritmosBusca);

        jMenuBar1.add(menuAlgoritmos);

        menuRelatorio.setText("Relatórios");

        jMenuItem15.setText("Relatório Ordenação");
        menuRelatorio.add(jMenuItem15);

        jMenuItem16.setText("Relatório Busca");
        menuRelatorio.add(jMenuItem16);

        jMenuBar1.add(menuRelatorio);

        menuAjuda.setText("Ajuda");

        jMenuItem5.setText("Conteúdo da Ajuda");
        menuAjuda.add(jMenuItem5);
        menuAjuda.add(jSeparator2);

        jMenuItem6.setText("Sobre");
        menuAjuda.add(jMenuItem6);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(barraStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArquivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoAbrirActionPerformed
        // TODO add your handling code here:
          FileFilter filter = new FileNameExtensionFilter("Arquivos de texto: txt, csv", "txt", "csv");
        fileChooser.addChoosableFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int returnVal = fileChooser.showOpenDialog(this);
        fileChooser.setMultiSelectionEnabled(false);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File arquivo = fileChooser.getSelectedFile();
            try (FileInputStream fi = new FileInputStream(arquivo)) {
                // What to do with the file, e.g. display it in a TextArea
                String cabecalho = "bugged_date;receipt_date;deputy_id;political_party;state_code;deputy_name;receipt_social_security_number;receipt_description;establishment_name;receipt_value";
                BufferedInputStream bis = new BufferedInputStream(fi);
                BufferedReader reader = new BufferedReader(new InputStreamReader(bis));
                String linha = linha = reader.readLine();
                if (linha.equals(cabecalho)) {
                    this.arquivo = arquivo;
                    nomeArquivoStatus.setText("Nome do arquivo:");
                    nomeArquivo.setText(arquivo.getName());
                    System.out.println(arquivo.getName());
                    JOptionPane.showMessageDialog(this, "Arquivo executado com sucesso!", "Abrir", JOptionPane.INFORMATION_MESSAGE);
                    ativaMenu();
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao abrir o arquivo!", "Abrir", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Falha ao abrir o arquivo!", "Abrir", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            
        }

    }//GEN-LAST:event_menuArquivoAbrirActionPerformed

    private void menuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuArquivoSairActionPerformed

    private void menuArquivoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoFecharActionPerformed
        // TODO add your handling code here:
        this.arquivo = null;
        desativaMenu();
    }//GEN-LAST:event_menuArquivoFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* */

 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }

    public void ativaMenu() {
        menuArquivoFechar.setEnabled(true);
        menuAlgoritmos.setEnabled(true);
    }

    public void desativaMenu() {
        menuArquivoFechar.setEnabled(false);
        menuAlgoritmos.setEnabled(false);
        nomeArquivoStatus.setText("Nenhum arquivo aberto");
        nomeArquivo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraStatus;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuAlgoritmos;
    private javax.swing.JMenu menuAlgoritmosBusca;
    private javax.swing.JMenu menuAlgoritmosOrdenacao;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuArquivoAbrir;
    private javax.swing.JMenuItem menuArquivoFechar;
    private javax.swing.JMenuItem menuArquivoSair;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JLabel nomeArquivo;
    private javax.swing.JLabel nomeArquivoStatus;
    // End of variables declaration//GEN-END:variables
}
